#line 2 "rtsl.lex.c"

#line 4 "rtsl.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 156
#define YY_END_OF_BUFFER 157
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[658] =
    {   0,
        0,    0,  149,  149,  157,  155,  154,  153,   47,   42,
       45,   36,   37,   26,   25,   32,   27,   33,   28,    4,
        4,   34,   35,   30,   29,   31,  145,  145,   40,   41,
       44,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,   38,   43,   39,
       46,  149,  148,  156,    9,   22,   12,   23,   20,   14,
       18,   15,   19,    6,  147,    0,   21,    7,    3,    0,
        4,    0,    4,   16,   10,    8,   11,   17,  145,  145,
       24,  145,  145,  145,  145,  145,  145,  145,  145,   72,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

       79,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,   13,  149,  151,  150,  152,    0,    6,    0,
      146,    6,    0,    7,    3,    0,    5,    2,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,   77,  145,  145,
      145,   49,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,    0,    6,    0,    6,    0,    7,
        5,    2,  107,  145,   51,  145,  145,   68,  145,  145,

      145,  145,  145,  145,  145,   74,  145,   75,  145,  145,
      145,  145,  145,   78,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,    1,  145,  145,  145,  145,  145,   52,
       53,   54,   48,  145,    0,    6,  145,   67,   58,   59,
       66,   95,  145,   69,  145,  145,  145,  145,  145,  145,
       50,  145,  145,  145,   55,   56,   57,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  145,  145,  119,  120,  145,  145,  106,  145,
      145,  145,  145,  145,  145,  145,   86,  145,  145,   88,
      145,  145,  145,  145,  145,   73,  145,  145,   76,  145,
      145,  145,  105,  145,   63,   89,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  132,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,   81,   80,   82,   83,   84,  145,  145,  145,  145,
      145,  145,  145,  145,   71,  145,  145,  145,  145,  145,
       64,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  125,  126,  130,  131,  135,  136,  145,  145,
       65,   85,   61,  145,   62,  145,  145,  145,  145,  145,
      145,   70,  110,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,   94,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,   87,   60,  145,  145,  145,  145,  145,  145,  145,
      145,  145,   98,  145,  145,  145,   91,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  104,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  115,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,   93,  145,
      108,  145,  145,  145,  145,   96,  109,   97,  145,  145,
      142,  145,  123,  122,  145,  145,  145,  145,  137,  145,
      145,  145,  145,  145,   92,  145,  145,  145,  145,  145,
      145,  145,  145,  121,  145,  145,  145,  145,  145,  111,
      144,  145,  145,  145,  145,  145,  118,  145,  145,  145,
       90,  145,  112,  145,  145,  145,  145,  128,   99,  145,
      100,  145,  145,  145,  145,  145,  145,  145,  140,  145,
      145,  145,  145,  145,  145,  145,  129,  145,  145,  103,

      145,  145,  145,  116,  145,  145,  145,  145,  143,  117,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      113,  145,  133,  145,  145,  141,  145,  145,  145,  145,
      139,  127,  145,  145,  145,  145,  145,  138,  102,  145,
      145,  124,  145,  145,  145,  145,  145,  134,  145,  145,
      145,  145,  114,  145,  145,  101,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   16,   16,   16,   16,   16,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   35,   36,   37,   38,   39,
       34,   40,   41,   42,   43,   44,   45,   46,   34,   34,
       47,    1,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   34,   60,   61,   62,   63,
       64,   65,   34,   66,   67,   68,   69,   70,   71,   72,
       73,   74,   75,   76,   77,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    4,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[664] =
    {   0,
        0,    0,   76,   77,  827,  828,  828,  828,  803,  802,
       75,  828,  828,  801,   72,  828,   71,   72,   83,   94,
       86,  828,  828,   94,  800,   95,    0,  781,  828,  828,
      798,  752,   56,   63,   29,   72,   87,   66,   89,  755,
       59,   88,  109,   66,  755,  106,  759,  828,  740,  828,
      828,    0,  828,  133,  828,  828,  828,  828,  828,  828,
      828,  828,  828,  156,  828,  812,  828,  172,  179,  214,
      828,    0,  222,  828,  828,  828,  828,  828,    0,  786,
      828,  745,  748,  756,  755,  742,  757,  120,  751,  737,
      738,  745,  734,  751,  733,  739,  735,  732,  734,  728,

        0,  734,  726,  738,  728,  732,  738,  721,  738,  725,
      720,  734,  119,   80,  725,  714,  717,   41,  715,  727,
      720,  719,  828,    0,  828,  828,  828,  237,  828,  774,
      828,  188,  251,  828,  828,  256,  263,  110,  746,  709,
      713,  722,  719,  716,  703,  705,  703,   97,  716,  714,
      710,  697,  701,  701,  706,  693,  708,    0,  703,  693,
      687,  700,  701,  693,  682,  690,  681,  294,  684,  697,
      693,  683,  690,  676,  674,  674,  686,  685,  157,  680,
      665,  197,  683,  675,  268,  281,  291,  828,  297,  323,
      828,  828,    0,  676,    0,  674,  182,    0,  666,  666,

      662,  662,  670,  659,  666,    0,  659,    0,  656,  658,
      668,  654,  655,    0,  658,  653,  240,  649,  666,  657,
      649,  178,  663,  158,  652,  657,  652,  647,   99,  658,
      222,  657,  292,  205,  289,  646,  638,  650,  649,  639,
      643,  648,  647,    0,  645,  634,  634,  639,  636,    0,
        0,    0,    0,  639,  345,  350,  641,    0,    0,    0,
        0,    0,  624,  625,  627,  628,  633,  628,  635,  622,
        0,  633,  624,  615,    0,    0,    0,  616,  612,  626,
      615,  649,  607,  613,  615,  606,  608,  607,  602,  599,
      605,  610,  598,  635,  605,  590,  600,  595,  609,  587,

      596,  603,  602,  601,    0,    0,  599,  600,    0,  598,
      595,  597,  581,  590,  592,  580,    0,  582,  581,    0,
      574,  587,  572,  571,  571,    0,  574,  569,    0,  568,
      572,  579,    0,  578,    0,    0,  602,  568,  575,  562,
      569,  576,  564,  197,  570,  557,  565,  567,    0,  559,
      264,  555,  564,  564,  549,  561,  140,  176,  220,  278,
      557,    0,    0,    0,    0,    0,  558,  551,  557,  554,
      542,  344,  556,  553,    0,  544,  551,  550,  553,  550,
        0,  303,  548,  535,  533,  538,  530,  542,  537,  531,
      528,  566,  524,  525,  531,  530,  522,  526,  531,  526,

      515,  542,    0,    0,    0,    0,    0,    0,  541,  553,
        0,    0,    0,  526,    0,  524,  514,  522,  512,  520,
      506,    0,    0,  534,  254,  504,  503,  515,  518,  532,
      516,  507,  501,  522,  495,  495,  502,  493,  495,  304,
      499,  489,  490,  496,  499,  490,  489,  485,  495,  521,
      518,    0,    0,  478,  480,  479,  472,  479,  514,  490,
      489,  480,    0,  483,  476,  295,    0,  472,  472,  479,
      467,  464,  468,  475,  465,  464,  468,  475,  466,  469,
      466,  495,  494,  463,  464,  463,  487,    0,  453,  456,
      452,  445,  446,  481,  437,  447,  444,  453,  437,  433,

      441,  440,    0,  430,  442,  449,  431,  458,  431,  435,
      285,  434,  424,  440,  433,  427,  426,  452,  328,  434,
        0,  433,  416,  434,  415,    0,    0,    0,  418,  419,
        0,  426,    0,    0,  453,  411,  425,  414,    0,  425,
      421,  410,  418,  404,    0,  416,  402,  406,  407,  403,
      402,  401,  420,    0,  396,  411,  400,  394,  398,    0,
        0,  394,  388,  419,  402,  381,    0,  387,  399,  400,
        0,  391,    0,  385,  382,  381,  385,  400,    0,  376,
        0,  388,  387,  380,  374,  375,  383,  409,    0,  368,
      372,  370,  367,  378,  369,  366,    0,  370,  401,    0,

      363,  371,  359,    0,  355,  346,  351,  340,    0,    0,
      351,  335,  330,  335,  332,  353,  334,  329,  330,  338,
        0,  331,    0,  336,  326,    0,  338,  337,  332,  322,
        0,    0,  317,  317,  321,  317,  324,    0,    0,  322,
      306,    0,  306,  314,  294,  263,  255,    0,  241,  225,
      199,  116,    0,  123,  102,    0,  828,  406,  408,  412,
      416,  420,   93
    } ;

static yyconst flex_int16_t yy_def[664] =
    {   0,
      657,    1,  658,  658,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  659,  659,  657,  657,
      657,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  657,  657,  657,
      657,  660,  657,  661,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  662,  657,  657,  657,  657,
      657,  663,  657,  657,  657,  657,  657,  657,  659,  659,
      657,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,

      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  657,  660,  657,  657,  657,  657,  657,  662,
      657,  657,  657,  657,  657,  657,  657,  663,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  657,  657,  657,  657,  657,  657,
      657,  657,  659,  659,  659,  659,  659,  659,  659,  659,

      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  657,  657,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,

      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,

      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,

      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,

      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,  659,  659,  659,  659,
      659,  659,  659,  659,  659,  659,    0,  657,  657,  657,
      657,  657,  657
    } ;

static yyconst flex_uint16_t yy_nxt[907] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   21,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   29,   30,   31,   27,
       32,   33,   34,   35,   36,   37,   38,   27,   39,   27,
       40,   27,   27,   27,   41,   42,   43,   44,   45,   46,
       47,   27,   27,   27,   48,   49,   50,   51,   53,   53,
       57,   60,   62,   89,   54,   54,   64,   64,   64,   64,
       64,   65,   90,   63,   61,  138,   66,   58,   68,  179,

       73,   73,   73,   73,   73,   67,   68,  180,   69,   69,
       69,   69,   69,   86,   70,   74,   75,   77,   78,   83,
       99,   84,   70,   87,  106,   85,   88,  107,   71,  100,
      174,  116,   91,   92,   93,  126,   71,   96,  117,   72,
       70,   94,  108,   95,  101,  175,  127,   97,   70,  102,
       98,  103,  192,  291,   71,  109,  119,  292,  104,  110,
      120,  111,   71,  202,  203,   72,  112,  113,  656,  121,
       64,   64,   64,   64,   64,  172,  114,  655,  192,  115,
      146,  147,  148,  654,  128,  129,  132,  132,  132,  132,
      132,   68,  173,   69,   69,   69,   69,   69,  259,  260,

      133,  134,  132,  132,  132,  132,  132,   70,  403,  404,
      128,  129,  246,  250,  251,  252,  187,  188,  282,  285,
      247,  135,  286,  136,  389,  136,  133,  134,  137,  137,
      137,  137,  137,   70,   68,  390,   73,   73,   73,   73,
       73,  283,  187,  188,  405,  406,  185,  135,  185,  294,
       70,  186,  186,  186,  186,  186,  275,  276,  277,  300,
      189,  653,  189,  301,   71,  190,  190,  190,  190,  190,
      137,  137,  137,  137,  137,  652,   70,  137,  137,  137,
      137,  137,  186,  186,  186,  186,  186,  295,  407,  408,
       71,  396,  191,  460,  461,  186,  186,  186,  186,  186,

      255,  397,  255,  409,  651,  256,  256,  256,  256,  256,
      129,  190,  190,  190,  190,  190,  410,  650,  191,  222,
      223,  649,  224,  225,  226,  227,  228,  302,  229,  230,
      476,  477,  231,  232,  233,  234,  129,  190,  190,  190,
      190,  190,  297,  428,  298,  500,  429,  235,  648,  299,
      543,  544,  134,  501,  552,  303,  304,  305,  306,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  417,
      553,  418,  647,  646,  645,  644,  643,  642,  134,  188,
      419,  641,  640,  639,  638,  420,  637,  636,  635,  634,
      633,  632,  631,  630,  629,  628,  627,  626,  625,  624,

      623,  622,  621,  620,  619,  188,   52,   52,   52,   52,
       79,   79,  124,  618,  124,  124,  125,  125,  125,  125,
      130,  130,  130,  130,  617,  616,  615,  614,  613,  612,
      611,  610,  609,  608,  607,  606,  605,  604,  603,  602,
      601,  600,  599,  598,  597,  596,  595,  594,  593,  592,
      591,  590,  589,  588,  587,  586,  585,  584,  583,  582,
      581,  580,  579,  578,  577,  576,  575,  574,  573,  572,
      571,  570,  569,  568,  567,  566,  565,  564,  563,  562,
      561,  560,  559,  558,  557,  556,  555,  554,  551,  550,
      549,  548,  547,  546,  545,  542,  541,  540,  539,  538,

      537,  536,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  519,  518,
      517,  516,  515,  514,  513,  512,  511,  510,  509,  508,
      507,  506,  505,  504,  503,  502,  499,  498,  497,  496,
      495,  494,  493,  492,  491,  490,  489,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  479,  478,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,
      463,  462,  459,  458,  457,  456,  455,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,

      431,  430,  427,  426,  425,  424,  423,  422,  421,  416,
      415,  414,  413,  412,  411,  402,  401,  400,  399,  398,
      395,  394,  393,  392,  391,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,

      313,  312,  311,  310,  309,  308,  307,  296,  293,  290,
      289,  288,  287,  284,  281,  280,  279,  278,  274,  273,
      272,  271,  244,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  258,  257,  254,  253,  249,  248,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  131,  184,  183,  182,
      181,  178,  177,  176,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,

      155,  154,  153,  152,  151,  150,  149,  145,  144,  143,
      142,  141,  140,  139,  131,  123,  122,  118,  105,   82,
       81,   80,   76,   59,   56,   55,  657,    5,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657
    } ;

static yyconst flex_int16_t yy_chk[907] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
       11,   15,   17,   35,    3,    4,   18,   18,   18,   18,
       18,   19,   35,   17,   15,  663,   19,   11,   21,  118,

       21,   21,   21,   21,   21,   19,   20,  118,   20,   20,
       20,   20,   20,   34,   21,   24,   24,   26,   26,   33,
       38,   33,   20,   34,   41,   33,   34,   41,   21,   38,
      114,   44,   36,   36,   36,   54,   20,   37,   44,   20,
       21,   36,   42,   36,   39,  114,   54,   37,   20,   39,
       37,   39,  138,  229,   21,   42,   46,  229,   39,   43,
       46,   43,   20,  148,  148,   20,   43,   43,  655,   46,
       64,   64,   64,   64,   64,  113,   43,  654,  138,   43,
       88,   88,   88,  652,   64,   64,   68,   68,   68,   68,
       68,   69,  113,   69,   69,   69,   69,   69,  197,  197,

       68,   68,  132,  132,  132,  132,  132,   69,  357,  357,
       64,   64,  179,  182,  182,  182,  132,  132,  222,  224,
      179,   69,  224,   70,  344,   70,   68,   68,   70,   70,
       70,   70,   70,   69,   73,  344,   73,   73,   73,   73,
       73,  222,  132,  132,  358,  358,  128,   69,  128,  231,
       73,  128,  128,  128,  128,  128,  217,  217,  217,  234,
      133,  651,  133,  234,   73,  133,  133,  133,  133,  133,
      136,  136,  136,  136,  136,  650,   73,  137,  137,  137,
      137,  137,  185,  185,  185,  185,  185,  231,  359,  359,
       73,  351,  137,  425,  425,  186,  186,  186,  186,  186,

      187,  351,  187,  360,  649,  187,  187,  187,  187,  187,
      186,  189,  189,  189,  189,  189,  360,  647,  137,  168,
      168,  646,  168,  168,  168,  168,  168,  235,  168,  168,
      440,  440,  168,  168,  168,  168,  186,  190,  190,  190,
      190,  190,  233,  382,  233,  466,  382,  168,  645,  233,
      511,  511,  190,  466,  519,  235,  235,  235,  235,  255,
      255,  255,  255,  255,  256,  256,  256,  256,  256,  372,
      519,  372,  644,  643,  641,  640,  637,  636,  190,  256,
      372,  635,  634,  633,  630,  372,  629,  628,  627,  625,
      624,  622,  620,  619,  618,  617,  616,  615,  614,  613,

      612,  611,  608,  607,  606,  256,  658,  658,  658,  658,
      659,  659,  660,  605,  660,  660,  661,  661,  661,  661,
      662,  662,  662,  662,  603,  602,  601,  599,  598,  596,
      595,  594,  593,  592,  591,  590,  588,  587,  586,  585,
      584,  583,  582,  580,  578,  577,  576,  575,  574,  572,
      570,  569,  568,  566,  565,  564,  563,  562,  559,  558,
      557,  556,  555,  553,  552,  551,  550,  549,  548,  547,
      546,  544,  543,  542,  541,  540,  538,  537,  536,  535,
      532,  530,  529,  525,  524,  523,  522,  520,  518,  517,
      516,  515,  514,  513,  512,  510,  509,  508,  507,  506,

      505,  504,  502,  501,  500,  499,  498,  497,  496,  495,
      494,  493,  492,  491,  490,  489,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  465,  464,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  424,  421,  420,  419,  418,  417,  416,  414,
      410,  409,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,

      384,  383,  380,  379,  378,  377,  376,  374,  373,  371,
      370,  369,  368,  367,  361,  356,  355,  354,  353,  352,
      350,  348,  347,  346,  345,  343,  342,  341,  340,  339,
      338,  337,  334,  332,  331,  330,  328,  327,  325,  324,
      323,  322,  321,  319,  318,  316,  315,  314,  313,  312,
      311,  310,  308,  307,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  274,  273,  272,  270,  269,  268,  267,  266,  265,
      264,  263,  257,  254,  249,  248,  247,  246,  245,  243,

      242,  241,  240,  239,  238,  237,  236,  232,  230,  228,
      227,  226,  225,  223,  221,  220,  219,  218,  216,  215,
      213,  212,  211,  210,  209,  207,  205,  204,  203,  202,
      201,  200,  199,  196,  194,  184,  183,  181,  180,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  130,  122,  121,  120,
      119,  117,  116,  115,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  100,   99,   98,   97,   96,

       95,   94,   93,   92,   91,   90,   89,   87,   86,   85,
       84,   83,   82,   80,   66,   49,   47,   45,   40,   32,
       31,   28,   25,   14,   10,    9,    5,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./rtsl.lex"
/**
  Compiler Design Course - TU Berlin
  Winter Term 2016/17

  Assignment 2
  YuAng Chen
  flex is based on Oliver`s solution
**/
#line 26 "./rtsl.lex"
#include <stdio.h>
#include "rtsl.yy.h"

int g_line_number = 1;


#line 904 "rtsl.lex.c"

#define INITIAL 0
#define ML_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 35 "./rtsl.lex"

#line 1125 "rtsl.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 658 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 828 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "./rtsl.lex"
{ return BOOL_CONSTANT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "./rtsl.lex"
{ return INT_CONSTANT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "./rtsl.lex"
{ return INT_CONSTANT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "./rtsl.lex"
{ return INT_CONSTANT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "./rtsl.lex"
{ return FLOAT_CONSTANT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "./rtsl.lex"
{ return FLOAT_CONSTANT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "./rtsl.lex"
{ return FLOAT_CONSTANT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "./rtsl.lex"
{ return EQ_OP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "./rtsl.lex"
{ return NE_OP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "./rtsl.lex"
{ return LE_OP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "./rtsl.lex"
{ return GE_OP; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "./rtsl.lex"
{ return AND_OP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "./rtsl.lex"
{ return OR_OP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "./rtsl.lex"
{ return INC_OP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "./rtsl.lex"
{ return DEC_OP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "./rtsl.lex"
{ return LEFT_OP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "./rtsl.lex"
{ return RIGHT_OP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "./rtsl.lex"
{ return ADD_ASSIGN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "./rtsl.lex"
{ return SUB_ASSIGN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "./rtsl.lex"
{ return MUL_ASSIGN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "./rtsl.lex"
{ return DIV_ASSIGN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "./rtsl.lex"
{ return MOD_ASSIGN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "./rtsl.lex"
{ return AND_ASSIGN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "./rtsl.lex"
{ return XOR_ASSIGN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "./rtsl.lex"
{ return '+'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "./rtsl.lex"
{ return '*'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "./rtsl.lex"
{ return '-'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "./rtsl.lex"
{ return '/'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "./rtsl.lex"
{ return '='; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "./rtsl.lex"
{ return '<'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "./rtsl.lex"
{ return '>'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "./rtsl.lex"
{ return ','; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "./rtsl.lex"
{ return '.'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "./rtsl.lex"
{ return ':'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "./rtsl.lex"
{ return ';'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "./rtsl.lex"
{ return '('; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "./rtsl.lex"
{ return ')'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "./rtsl.lex"
{ return '{'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "./rtsl.lex"
{ return '}'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "./rtsl.lex"
{ return '['; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "./rtsl.lex"
{ return ']'; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "./rtsl.lex"
{ return '%'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "./rtsl.lex"
{ return '|'; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "./rtsl.lex"
{ return '^'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "./rtsl.lex"
{ return '%'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "./rtsl.lex"
{ return '~'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "./rtsl.lex"
{ return '!'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "./rtsl.lex"
{ return VOID; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 86 "./rtsl.lex"
{ return INT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "./rtsl.lex"
{ return FLOAT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "./rtsl.lex"
{ return BOOL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "./rtsl.lex"
{ return VEC2; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "./rtsl.lex"
{ return VEC3; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "./rtsl.lex"
{ return VEC4; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "./rtsl.lex"
{ return IVEC2; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 93 "./rtsl.lex"
{ return IVEC3; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 94 "./rtsl.lex"
{ return IVEC4; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "./rtsl.lex"
{ return BVEC2; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 96 "./rtsl.lex"
{ return BVEC3; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "./rtsl.lex"
{ return ATTRIBUTE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "./rtsl.lex"
{ return UNIFORM; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "./rtsl.lex"
{ return VARYING; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "./rtsl.lex"
{ return PUBLIC; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "./rtsl.lex"
{ return PRIVATE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "./rtsl.lex"
{ return SCRATCH; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "./rtsl.lex"
{ return CLASS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "./rtsl.lex"
{ return BREAK; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "./rtsl.lex"
{ return CASE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "./rtsl.lex"
{ return CONST; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "./rtsl.lex"
{ return CONTINUE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 110 "./rtsl.lex"
{ return DEFAULT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 111 "./rtsl.lex"
{ return DO; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 112 "./rtsl.lex"
{ return DOUBLE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 113 "./rtsl.lex"
{ return ELSE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 114 "./rtsl.lex"
{ return ENUM; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 115 "./rtsl.lex"
{ return EXTERN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 116 "./rtsl.lex"
{ return FOR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 117 "./rtsl.lex"
{ return GOTO; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 118 "./rtsl.lex"
{ return IF; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 119 "./rtsl.lex"
{ return SIZEOF; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 120 "./rtsl.lex"
{ return SIGNED; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "./rtsl.lex"
{ return STATIC; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 122 "./rtsl.lex"
{ return STRUCT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "./rtsl.lex"
{ return SWITCH; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "./rtsl.lex"
{ return TYPEDEF; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "./rtsl.lex"
{ return UNION; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 126 "./rtsl.lex"
{ return UNSIGNED; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 127 "./rtsl.lex"
{ return WHILE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 128 "./rtsl.lex"
{ return RETURN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "./rtsl.lex"
{ return PRIMITIVE;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 131 "./rtsl.lex"
{ return CAMERA;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 132 "./rtsl.lex"
{ return MATERIAL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 133 "./rtsl.lex"
{ return TEXTURE;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 134 "./rtsl.lex"
{ return LIGHT;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 135 "./rtsl.lex"
{ return COLOR;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 137 "./rtsl.lex"
{ return CONSTRUCTOR;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 138 "./rtsl.lex"
{ return GENERATERAY;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 139 "./rtsl.lex"
{ return INTERSECT;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 140 "./rtsl.lex"
{ return COMPUTEBOUNDS;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 141 "./rtsl.lex"
{ return COMPUTENORMAL;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 142 "./rtsl.lex"
{ return COMPUTETEXTURECOORDINATES;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 143 "./rtsl.lex"
{ return COMPUTEDERIVATIVES;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 144 "./rtsl.lex"
{ return GENERATESAMPLE;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 145 "./rtsl.lex"
{ return SAMPLEPDF;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 146 "./rtsl.lex"
{ return LOOKUP;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 147 "./rtsl.lex"
{ return SHADE;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 148 "./rtsl.lex"
{ return BSDF;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 149 "./rtsl.lex"
{ return SAMPLEBSDF;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 150 "./rtsl.lex"
{ return EVALUATEPDF;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 151 "./rtsl.lex"
{ return EMISSION;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 152 "./rtsl.lex"
{ return ILLUMINATION;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 154 "./rtsl.lex"
{ return RAYORIGIN;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 155 "./rtsl.lex"
{ return RAYDIRECTION;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 156 "./rtsl.lex"
{ return INVERSERAYDIRECTION;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 157 "./rtsl.lex"
{ return EPSILON;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 158 "./rtsl.lex"
{ return HITDISTANCE;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 159 "./rtsl.lex"
{ return SCREENCOORD;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 160 "./rtsl.lex"
{ return LENSCOORD;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 161 "./rtsl.lex"
{ return DU;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 162 "./rtsl.lex"
{ return DV;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 163 "./rtsl.lex"
{ return TIMESEED;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 164 "./rtsl.lex"
{ return BOUNDMIN;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 165 "./rtsl.lex"
{ return BOUNDMAX;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 166 "./rtsl.lex"
{ return GEOMETRICNORMAL;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 167 "./rtsl.lex"
{ return DPDU;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 168 "./rtsl.lex"
{ return DPDV;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 169 "./rtsl.lex"
{ return SHADINGNORMAL;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 170 "./rtsl.lex"
{ return TEXTUREUV;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 171 "./rtsl.lex"
{ return TEXTUREUVW;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 172 "./rtsl.lex"
{ return DSDU;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 173 "./rtsl.lex"
{ return DSDV;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 174 "./rtsl.lex"
{ return PDF;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 175 "./rtsl.lex"
{ return TEXTURECOLOR;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 176 "./rtsl.lex"
{ return FLOATTEXTUREVALUE;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 177 "./rtsl.lex"
{ return DTDU;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 178 "./rtsl.lex"
{ return DTDV;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 179 "./rtsl.lex"
{ return HITPOINT;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 180 "./rtsl.lex"
{ return LIGHTDIRECTION;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 181 "./rtsl.lex"
{ return LIGHTDISTANCE;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 182 "./rtsl.lex"
{ return LIGHTCOLOR;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 183 "./rtsl.lex"
{ return EMISSIONCOLOR;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 184 "./rtsl.lex"
{ return BSDFSEED;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 185 "./rtsl.lex"
{ return SAMPLECOLOR;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 186 "./rtsl.lex"
{ return BSDFVALUE;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 190 "./rtsl.lex"
{ return IDENTIFIER; }
	YY_BREAK
case 146:
/* rule 146 can match eol */
YY_RULE_SETUP
#line 192 "./rtsl.lex"
{ ++g_line_number; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 193 "./rtsl.lex"
{ BEGIN(ML_COMMENT); }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 195 "./rtsl.lex"
{ ++g_line_number; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 196 "./rtsl.lex"
{ ; }
	YY_BREAK
case 150:
/* rule 150 can match eol */
YY_RULE_SETUP
#line 197 "./rtsl.lex"
{ ++g_line_number; }
	YY_BREAK
case 151:
/* rule 151 can match eol */
YY_RULE_SETUP
#line 198 "./rtsl.lex"
{ ; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 199 "./rtsl.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 153:
/* rule 153 can match eol */
YY_RULE_SETUP
#line 201 "./rtsl.lex"
{ ++g_line_number; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 202 "./rtsl.lex"
{ ; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 203 "./rtsl.lex"
{  }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 204 "./rtsl.lex"
ECHO;
	YY_BREAK
#line 1967 "rtsl.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 658 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 658 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 657);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 204 "./rtsl.lex"



